# Generated by Django 5.0.7 on 2024-08-15 02:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='advertisment',
            name='url',
            field=models.URLField(blank=True, null=True),
        ),
    ]
