# Generated by Django 5.0.7 on 2024-08-11 13:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_rename_country_city_state'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='address',
            name='state',
        ),
    ]
